"""add_backoffice_page_registry.

Revision ID: 0002_backoffice_page_registry
Revises: 0001_d2c_backoffice_baseline
Create Date: 2026-05-23

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_backoffice_page_registry"
down_revision: str | Sequence[str] | None = "0001_d2c_backoffice_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PAGE_ROWS = [
    {
        "page_code": "d2c.backoffice.operations",
        "parent_code": None,
        "level": 1,
        "title": "经营首页",
        "route_path": "/operations",
        "component_key": "layout.group",
        "icon": "home",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.operations.dashboard",
        "parent_code": "d2c.backoffice.operations",
        "level": 2,
        "title": "经营总览",
        "route_path": "/operations/dashboard",
        "component_key": "layout.group",
        "icon": "dashboard",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.operations.dashboard.overview",
        "parent_code": "d2c.backoffice.operations.dashboard",
        "level": 3,
        "title": "经营总览",
        "route_path": "/operations/dashboard/overview",
        "component_key": "dashboard.overview",
        "icon": "dashboard",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing",
        "parent_code": None,
        "level": 1,
        "title": "商品与价格",
        "route_path": "/catalog-pricing",
        "component_key": "layout.group",
        "icon": "box",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.catalog",
        "parent_code": "d2c.backoffice.catalog_pricing",
        "level": 2,
        "title": "商品管理",
        "route_path": "/catalog-pricing/catalog",
        "component_key": "layout.group",
        "icon": "box",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.catalog.products",
        "parent_code": "d2c.backoffice.catalog_pricing.catalog",
        "level": 3,
        "title": "商品列表",
        "route_path": "/catalog-pricing/catalog/products",
        "component_key": "catalog.products",
        "icon": "box",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.catalog.skus",
        "parent_code": "d2c.backoffice.catalog_pricing.catalog",
        "level": 3,
        "title": "SKU 列表",
        "route_path": "/catalog-pricing/catalog/skus",
        "component_key": "catalog.skus",
        "icon": "barcode",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.catalog.categories",
        "parent_code": "d2c.backoffice.catalog_pricing.catalog",
        "level": 3,
        "title": "类目管理",
        "route_path": "/catalog-pricing/catalog/categories",
        "component_key": "catalog.categories",
        "icon": "folder",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.catalog.units",
        "parent_code": "d2c.backoffice.catalog_pricing.catalog",
        "level": 3,
        "title": "单位管理",
        "route_path": "/catalog-pricing/catalog/units",
        "component_key": "catalog.units",
        "icon": "ruler",
        "sort_order": 40,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.pricing",
        "parent_code": "d2c.backoffice.catalog_pricing",
        "level": 2,
        "title": "价格管理",
        "route_path": "/catalog-pricing/pricing",
        "component_key": "layout.group",
        "icon": "tag",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.pricing.price_lists",
        "parent_code": "d2c.backoffice.catalog_pricing.pricing",
        "level": 3,
        "title": "价格表",
        "route_path": "/catalog-pricing/pricing/price-lists",
        "component_key": "pricing.price_lists",
        "icon": "tag",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.catalog_pricing.pricing.sku_prices",
        "parent_code": "d2c.backoffice.catalog_pricing.pricing",
        "level": 3,
        "title": "SKU 价格",
        "route_path": "/catalog-pricing/pricing/sku-prices",
        "component_key": "pricing.sku_prices",
        "icon": "tag",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment",
        "parent_code": None,
        "level": 1,
        "title": "订单与履约",
        "route_path": "/orders-fulfillment",
        "component_key": "layout.group",
        "icon": "orders",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.orders",
        "parent_code": "d2c.backoffice.orders_fulfillment",
        "level": 2,
        "title": "订单管理",
        "route_path": "/orders-fulfillment/orders",
        "component_key": "layout.group",
        "icon": "orders",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.orders.list",
        "parent_code": "d2c.backoffice.orders_fulfillment.orders",
        "level": 3,
        "title": "订单列表",
        "route_path": "/orders-fulfillment/orders/list",
        "component_key": "orders.list",
        "icon": "orders",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.orders.pending_payment",
        "parent_code": "d2c.backoffice.orders_fulfillment.orders",
        "level": 3,
        "title": "待支付订单",
        "route_path": "/orders-fulfillment/orders/pending-payment",
        "component_key": "orders.pending_payment",
        "icon": "orders",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.orders.paid",
        "parent_code": "d2c.backoffice.orders_fulfillment.orders",
        "level": 3,
        "title": "已支付订单",
        "route_path": "/orders-fulfillment/orders/paid",
        "component_key": "orders.paid",
        "icon": "orders",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.orders.detail",
        "parent_code": "d2c.backoffice.orders_fulfillment.orders",
        "level": 3,
        "title": "订单详情",
        "route_path": "/orders-fulfillment/orders/detail",
        "component_key": "orders.detail",
        "icon": "orders",
        "sort_order": 40,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.payments",
        "parent_code": "d2c.backoffice.orders_fulfillment",
        "level": 2,
        "title": "支付管理",
        "route_path": "/orders-fulfillment/payments",
        "component_key": "layout.group",
        "icon": "payment",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.payments.records",
        "parent_code": "d2c.backoffice.orders_fulfillment.payments",
        "level": 3,
        "title": "支付记录",
        "route_path": "/orders-fulfillment/payments/records",
        "component_key": "payments.records",
        "icon": "payment",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.payments.exceptions",
        "parent_code": "d2c.backoffice.orders_fulfillment.payments",
        "level": 3,
        "title": "支付异常",
        "route_path": "/orders-fulfillment/payments/exceptions",
        "component_key": "payments.exceptions",
        "icon": "payment",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.fulfillment",
        "parent_code": "d2c.backoffice.orders_fulfillment",
        "level": 2,
        "title": "发货履约",
        "route_path": "/orders-fulfillment/fulfillment",
        "component_key": "layout.group",
        "icon": "truck",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.fulfillment.awaiting_shipment",
        "parent_code": "d2c.backoffice.orders_fulfillment.fulfillment",
        "level": 3,
        "title": "待发货",
        "route_path": "/orders-fulfillment/fulfillment/awaiting-shipment",
        "component_key": "fulfillment.awaiting_shipment",
        "icon": "truck",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.orders_fulfillment.fulfillment.shipped",
        "parent_code": "d2c.backoffice.orders_fulfillment.fulfillment",
        "level": 3,
        "title": "已发货",
        "route_path": "/orders-fulfillment/fulfillment/shipped",
        "component_key": "fulfillment.shipped",
        "icon": "truck",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.marketing",
        "parent_code": None,
        "level": 1,
        "title": "营销中心",
        "route_path": "/marketing",
        "component_key": "layout.group",
        "icon": "marketing",
        "sort_order": 40,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.promotions",
        "parent_code": "d2c.backoffice.marketing",
        "level": 2,
        "title": "促销管理",
        "route_path": "/marketing/promotions",
        "component_key": "layout.group",
        "icon": "marketing",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.promotions.list",
        "parent_code": "d2c.backoffice.marketing.promotions",
        "level": 3,
        "title": "促销活动",
        "route_path": "/marketing/promotions/list",
        "component_key": "promotions.list",
        "icon": "marketing",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.promotions.targets",
        "parent_code": "d2c.backoffice.marketing.promotions",
        "level": 3,
        "title": "促销目标",
        "route_path": "/marketing/promotions/targets",
        "component_key": "promotions.targets",
        "icon": "target",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.coupons",
        "parent_code": "d2c.backoffice.marketing",
        "level": 2,
        "title": "优惠券管理",
        "route_path": "/marketing/coupons",
        "component_key": "layout.group",
        "icon": "coupon",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.coupons.list",
        "parent_code": "d2c.backoffice.marketing.coupons",
        "level": 3,
        "title": "优惠券列表",
        "route_path": "/marketing/coupons/list",
        "component_key": "coupons.list",
        "icon": "coupon",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.marketing.coupons.customer_usage",
        "parent_code": "d2c.backoffice.marketing.coupons",
        "level": 3,
        "title": "顾客优惠券核销",
        "route_path": "/marketing/coupons/customer-usage",
        "component_key": "coupons.customer_usage",
        "icon": "coupon",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.customer_ops",
        "parent_code": None,
        "level": 1,
        "title": "顾客运营",
        "route_path": "/customer-ops",
        "component_key": "layout.group",
        "icon": "customers",
        "sort_order": 50,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.customers",
        "parent_code": "d2c.backoffice.customer_ops",
        "level": 2,
        "title": "顾客管理",
        "route_path": "/customer-ops/customers",
        "component_key": "layout.group",
        "icon": "customers",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.customers.list",
        "parent_code": "d2c.backoffice.customer_ops.customers",
        "level": 3,
        "title": "顾客列表",
        "route_path": "/customer-ops/customers/list",
        "component_key": "customers.list",
        "icon": "customers",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.customers.detail",
        "parent_code": "d2c.backoffice.customer_ops.customers",
        "level": 3,
        "title": "顾客详情",
        "route_path": "/customer-ops/customers/detail",
        "component_key": "customers.detail",
        "icon": "customers",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.assets",
        "parent_code": "d2c.backoffice.customer_ops",
        "level": 2,
        "title": "顾客资产",
        "route_path": "/customer-ops/assets",
        "component_key": "layout.group",
        "icon": "customers",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.assets.orders",
        "parent_code": "d2c.backoffice.customer_ops.assets",
        "level": 3,
        "title": "顾客订单",
        "route_path": "/customer-ops/assets/orders",
        "component_key": "customers.orders",
        "icon": "orders",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.assets.coupons",
        "parent_code": "d2c.backoffice.customer_ops.assets",
        "level": 3,
        "title": "顾客优惠券",
        "route_path": "/customer-ops/assets/coupons",
        "component_key": "customers.coupons",
        "icon": "coupon",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.customer_ops.assets.addresses",
        "parent_code": "d2c.backoffice.customer_ops.assets",
        "level": 3,
        "title": "顾客地址",
        "route_path": "/customer-ops/assets/addresses",
        "component_key": "customers.addresses",
        "icon": "map",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics",
        "parent_code": None,
        "level": 1,
        "title": "数据分析",
        "route_path": "/analytics",
        "component_key": "layout.group",
        "icon": "analytics",
        "sort_order": 60,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.behavior",
        "parent_code": "d2c.backoffice.analytics",
        "level": 2,
        "title": "行为分析",
        "route_path": "/analytics/behavior",
        "component_key": "layout.group",
        "icon": "analytics",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.behavior.product_views",
        "parent_code": "d2c.backoffice.analytics.behavior",
        "level": 3,
        "title": "浏览行为",
        "route_path": "/analytics/behavior/product-views",
        "component_key": "analytics.behavior.product_views",
        "icon": "analytics",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.behavior.add_to_cart",
        "parent_code": "d2c.backoffice.analytics.behavior",
        "level": 3,
        "title": "加购行为",
        "route_path": "/analytics/behavior/add-to-cart",
        "component_key": "analytics.behavior.add_to_cart",
        "icon": "analytics",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.behavior.checkout",
        "parent_code": "d2c.backoffice.analytics.behavior",
        "level": 3,
        "title": "结算行为",
        "route_path": "/analytics/behavior/checkout",
        "component_key": "analytics.behavior.checkout",
        "icon": "analytics",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.funnel",
        "parent_code": "d2c.backoffice.analytics",
        "level": 2,
        "title": "转化漏斗",
        "route_path": "/analytics/funnel",
        "component_key": "layout.group",
        "icon": "funnel",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.funnel.view_to_cart",
        "parent_code": "d2c.backoffice.analytics.funnel",
        "level": 3,
        "title": "浏览到加购",
        "route_path": "/analytics/funnel/view-to-cart",
        "component_key": "analytics.funnel.view_to_cart",
        "icon": "funnel",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.funnel.cart_to_checkout",
        "parent_code": "d2c.backoffice.analytics.funnel",
        "level": 3,
        "title": "加购到结算",
        "route_path": "/analytics/funnel/cart-to-checkout",
        "component_key": "analytics.funnel.cart_to_checkout",
        "icon": "funnel",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.funnel.checkout_to_paid",
        "parent_code": "d2c.backoffice.analytics.funnel",
        "level": 3,
        "title": "结算到支付",
        "route_path": "/analytics/funnel/checkout-to-paid",
        "component_key": "analytics.funnel.checkout_to_paid",
        "icon": "funnel",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.marketing",
        "parent_code": "d2c.backoffice.analytics",
        "level": 2,
        "title": "营销分析",
        "route_path": "/analytics/marketing",
        "component_key": "layout.group",
        "icon": "analytics",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.marketing.promotions",
        "parent_code": "d2c.backoffice.analytics.marketing",
        "level": 3,
        "title": "促销效果",
        "route_path": "/analytics/marketing/promotions",
        "component_key": "analytics.marketing.promotions",
        "icon": "analytics",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.analytics.marketing.coupons",
        "parent_code": "d2c.backoffice.analytics.marketing",
        "level": 3,
        "title": "优惠券效果",
        "route_path": "/analytics/marketing/coupons",
        "component_key": "analytics.marketing.coupons",
        "icon": "analytics",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings",
        "parent_code": None,
        "level": 1,
        "title": "店铺设置",
        "route_path": "/settings",
        "component_key": "layout.group",
        "icon": "settings",
        "sort_order": 70,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.store",
        "parent_code": "d2c.backoffice.settings",
        "level": 2,
        "title": "店铺资料",
        "route_path": "/settings/store",
        "component_key": "layout.group",
        "icon": "settings",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.store.basic",
        "parent_code": "d2c.backoffice.settings.store",
        "level": 3,
        "title": "基本信息",
        "route_path": "/settings/store/basic",
        "component_key": "settings.store.basic",
        "icon": "settings",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.trade",
        "parent_code": "d2c.backoffice.settings",
        "level": 2,
        "title": "交易设置",
        "route_path": "/settings/trade",
        "component_key": "layout.group",
        "icon": "settings",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.trade.payments",
        "parent_code": "d2c.backoffice.settings.trade",
        "level": 3,
        "title": "支付方式",
        "route_path": "/settings/trade/payments",
        "component_key": "settings.trade.payments",
        "icon": "payment",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.trade.shipping",
        "parent_code": "d2c.backoffice.settings.trade",
        "level": 3,
        "title": "配送区域",
        "route_path": "/settings/trade/shipping",
        "component_key": "settings.trade.shipping",
        "icon": "truck",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.ops",
        "parent_code": "d2c.backoffice.settings",
        "level": 2,
        "title": "运营设置",
        "route_path": "/settings/ops",
        "component_key": "layout.group",
        "icon": "settings",
        "sort_order": 30,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.ops.currency",
        "parent_code": "d2c.backoffice.settings.ops",
        "level": 3,
        "title": "默认币种",
        "route_path": "/settings/ops/currency",
        "component_key": "settings.ops.currency",
        "icon": "settings",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.settings.ops.price_list",
        "parent_code": "d2c.backoffice.settings.ops",
        "level": 3,
        "title": "默认价格表",
        "route_path": "/settings/ops/price-list",
        "component_key": "settings.ops.price_list",
        "icon": "settings",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.system",
        "parent_code": None,
        "level": 1,
        "title": "系统管理",
        "route_path": "/system",
        "component_key": "layout.group",
        "icon": "system",
        "sort_order": 80,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.system.accounts",
        "parent_code": "d2c.backoffice.system",
        "level": 2,
        "title": "账号与权限",
        "route_path": "/system/accounts",
        "component_key": "layout.group",
        "icon": "users",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.system.accounts.users",
        "parent_code": "d2c.backoffice.system.accounts",
        "level": 3,
        "title": "商家账号",
        "route_path": "/system/accounts/users",
        "component_key": "system.accounts.users",
        "icon": "users",
        "sort_order": 10,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.system.accounts.roles",
        "parent_code": "d2c.backoffice.system.accounts",
        "level": 3,
        "title": "角色权限",
        "route_path": "/system/accounts/roles",
        "component_key": "system.accounts.roles",
        "icon": "users",
        "sort_order": 20,
        "implementation_status": "planned",
        "data_status": "placeholder",
    },
    {
        "page_code": "d2c.backoffice.system.pages",
        "parent_code": "d2c.backoffice.system",
        "level": 2,
        "title": "页面目录",
        "route_path": "/system/pages",
        "component_key": "layout.group",
        "icon": "pages",
        "sort_order": 20,
        "implementation_status": "ready",
        "data_status": "connected",
    },
    {
        "page_code": "d2c.backoffice.system.pages.registry",
        "parent_code": "d2c.backoffice.system.pages",
        "level": 3,
        "title": "页面注册",
        "route_path": "/system/pages/registry",
        "component_key": "system.pages.registry",
        "icon": "pages",
        "sort_order": 10,
        "implementation_status": "ready",
        "data_status": "connected",
    },
]


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        "d2c_backoffice_pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("page_code", sa.String(length=160), nullable=False),
        sa.Column("parent_code", sa.String(length=160), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("route_path", sa.String(length=240), nullable=False),
        sa.Column("component_key", sa.String(length=160), nullable=False),
        sa.Column("icon", sa.String(length=80), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_visible", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "implementation_status",
            sa.String(length=32),
            nullable=False,
            server_default="planned",
        ),
        sa.Column(
            "data_status",
            sa.String(length=32),
            nullable=False,
            server_default="placeholder",
        ),
        sa.Column("required_permission", sa.String(length=160), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_code", name="uq_d2c_backoffice_pages_page_code"),
    )
    op.create_index(
        "ix_d2c_backoffice_pages_parent_code",
        "d2c_backoffice_pages",
        ["parent_code"],
    )
    op.create_index(
        "ix_d2c_backoffice_pages_route_path",
        "d2c_backoffice_pages",
        ["route_path"],
    )
    op.create_index(
        "ix_d2c_backoffice_pages_sort_order",
        "d2c_backoffice_pages",
        ["sort_order"],
    )

    pages_table = sa.table(
        "d2c_backoffice_pages",
        sa.column("page_code", sa.String),
        sa.column("parent_code", sa.String),
        sa.column("level", sa.Integer),
        sa.column("title", sa.String),
        sa.column("route_path", sa.String),
        sa.column("component_key", sa.String),
        sa.column("icon", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_enabled", sa.Boolean),
        sa.column("is_visible", sa.Boolean),
        sa.column("implementation_status", sa.String),
        sa.column("data_status", sa.String),
        sa.column("required_permission", sa.String),
    )

    op.bulk_insert(
        pages_table,
        [
            {
                "page_code": page["page_code"],
                "parent_code": page["parent_code"],
                "level": page["level"],
                "title": page["title"],
                "route_path": page["route_path"],
                "component_key": page["component_key"],
                "icon": page["icon"],
                "sort_order": page["sort_order"],
                "is_enabled": True,
                "is_visible": True,
                "implementation_status": page["implementation_status"],
                "data_status": page["data_status"],
                "required_permission": None,
            }
            for page in PAGE_ROWS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index("ix_d2c_backoffice_pages_sort_order", table_name="d2c_backoffice_pages")
    op.drop_index("ix_d2c_backoffice_pages_route_path", table_name="d2c_backoffice_pages")
    op.drop_index("ix_d2c_backoffice_pages_parent_code", table_name="d2c_backoffice_pages")
    op.drop_table("d2c_backoffice_pages")
